use_frameworks!

platform :ios, '9.0'

target 'ADYLiveSDK_iOS_Example' do
  pod 'ADYLiveSDK_iOS', :path => '../'

  target 'ADYLiveSDK_iOS_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
